### ISSUE TITLE
Doesn't work with Vim Plug  

### ISSUE THREAD

**Issue by Sanix-Darker** [princejoogie/chafa.nvim#2]
Am on nvim nightly and using Vim-Plug !
Inside my plugins.vim i have : 
```
Plug 'm00qek/baleia.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'rincejoogie/chafa.nvim'
```
When am trying to install `:PlugInstall`

Am getting an error when cloning it : 
```
x chafa.nvim:
    Cloning into '/home/dk/.config/nvim/plugged/chafa.nvim'...
    fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

**Comment by princejoogie** [comment]
> Plug 'rincejoogie/chafa.nvim'

i think you missed a `p` it should be `Plug 'princejoogie/chafa.nvim'`

**Comment by Sanix-Darker** [comment]
OOOOhhh mannn 🤦🏽‍♂️ 
Sorry about that !
