### ISSUE TITLE
Remove assets from git repo

### ISSUE THREAD

**Issue by Amar1729** [princejoogie/chafa.nvim#3]
Even though the `assets/` directory is not very large (9mb) would you mind removing them from the git repo and uploading them as assets directly to github instead? It's not a huge hit, but they are 9mb vs the ~35kb of the rest of the files in the repo.

https://www.reddit.com/r/neovim/comments/wsg5yx/attention_to_all_plugin_authors_newcomers_careful/

**Comment by princejoogie** [comment]
thanks for the feedback!
