### ISSUE TITLE
setup options don't seem to be respected (or maybe just show_label?)

### ISSUE THREAD

**Issue by technicalpickles** [princejoogie/chafa.nvim#5]
I have this setup:

```lua
require("chafa").setup({
	min_padding = 0,
	show_label = false,
})
```

I'm still seeing labels though:

![Screenshot 2023-01-14 at 11 31 03 AM](https://user-images.githubusercontent.com/159/212483445-5f78853a-be87-4493-aea8-f889ac57460b.png)

**Comment by Frederick888** [comment]
Those settings are in `render`. Just copy the example configuration, mate :shrug:

**Comment by technicalpickles** [comment]
Oops 😮‍💨  I shuffled options around a few times, and must have lost the `render`.
