### ISSUE TITLE
Chafa support in image.nvim

### ISSUE THREAD

**Issue by samodostal** [princejoogie/chafa.nvim#9]
Hey,
I will be implementing different engine support in my 'image.nvim' plugin soon. Would you be interested in submitting a PR for 'chafa' support?
Also please look at the MIT license compliance, as this is a fork of my plugin. Thanks.

**Comment by princejoogie** [comment]
Will look into it, thanks!

**Comment by hpjansson** [comment]
I'm adding more QoL features in the next Chafa release with an eye towards easier integration. If there's anything you need in particular, let me know!
